### ISSUE TITLE
Does not work with Heroku

### ISSUE THREAD

**Issue by shortycake** [koopjs/koop-sample-app#31]
heroku deployment doesn't work, it crashes and also it is not clear how to connect to a postgis database with the sample app

**Comment by jgravois** [comment]
this problem was reported in #27
the last time i looked, PostGIS was not available in Heroku's free tier.  i'll try to find some time soon to see if thats still the case and if so, make sure we have a sample that uses an `IN_MEMORY` cache that is easy to deploy.

i'm going to go ahead and close this one out, but feel free to reply to the other if you have additional questions.

**Comment by ungoldman** [comment]
Still a valid point. A lot of work was done to try to make koop work out of the box with minimal setup on PaaS providers like Heroku. I think it's still possible with the current codebase. Maybe removing the postgis plugin from the starter app would help?

**Comment by shortycake** [comment]
Yeah. The way it is now you can't use koopjs-sample-app with Heroku. It will just automatically crash because you can't connect to a database. 

You can certainly get PostGIS with Heroku which is what I was interested in doing... I committed a lot of time and effort to understanding koop :) now I have no idea how I can use it... since heroku, AWS and other cloud services whatever are not supported... what am I supposed to do exactly :P

**Comment by jgravois** [comment]
@shortycake can you click the button below and let me know if the instance thats deployed is functional?

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/koopjs/koop-sample-app/tree/heroku)

more info [here](https://github.com/koopjs/koop-sample-app/blob/heroku/HEROKU.md).

**Comment by shortycake** [comment]
That one is functional and worked, jgravois
