### ISSUE TITLE
error: Could not connect to the database: getaddrinfo

### ISSUE THREAD

**Issue by ca0v** [koopjs/koop-sample-app#33]
Tried it out, quickly reports error: Could not connect to the database: getaddrinfo.

But I guess looking at the code was the point of this exercise anyway.

**Comment by dmfenton** [comment]
I think your problem is that you do not have postgres running locally or the config doesn't match the port or address of your database.

In any event, this sample needs to be updated for Koop 3.0. Until that happens, I'd recommend checking out: https://github.com/koopjs/koop-sample-provider/blob/master/server.js
